-- 1) Tabela
create table if not exists public.mensagens_modelos (
  id bigserial primary key,
  owner_id uuid null,
  titulo text null,
  conteudo text not null,
  created_at timestamptz not null default now()
);

-- Índices (opcional, melhora ordenação/busca)
create index if not exists mensagens_modelos_created_at_idx
  on public.mensagens_modelos (created_at desc);

create index if not exists mensagens_modelos_owner_id_idx
  on public.mensagens_modelos (owner_id nulls last);

-- 2) Habilitar RLS
alter table public.mensagens_modelos enable row level security;

-- 3) Limpar policies antigas para não conflitar
drop policy if exists mensagens_modelos_select_anon on public.mensagens_modelos;
drop policy if exists mensagens_modelos_insert_anon on public.mensagens_modelos;
drop policy if exists mensagens_modelos_delete_anon on public.mensagens_modelos;

drop policy if exists mensagens_modelos_select_auth on public.mensagens_modelos;
drop policy if exists mensagens_modelos_insert_auth on public.mensagens_modelos;
drop policy if exists mensagens_modelos_update_auth on public.mensagens_modelos;
drop policy if exists mensagens_modelos_delete_auth on public.mensagens_modelos;

-- 4) Policies para usuários sem login (anon)
-- Ver/usar mensagens públicas (owner_id IS NULL)
create policy mensagens_modelos_select_anon
  on public.mensagens_modelos
  for select
  to anon
  using (owner_id is null);

-- Criar mensagens públicas (sem login)
create policy mensagens_modelos_insert_anon
  on public.mensagens_modelos
  for insert
  to anon
  with check (owner_id is null);

-- Apagar mensagens públicas (sem login)
create policy mensagens_modelos_delete_anon
  on public.mensagens_modelos
  for delete
  to anon
  using (owner_id is null);

-- 5) Policies para usuários logados (authenticated)
-- Pode ver públicas e as próprias
create policy mensagens_modelos_select_auth
  on public.mensagens_modelos
  for select
  to authenticated
  using (owner_id = auth.uid() or owner_id is null);

-- Pode inserir públicas (owner_id IS NULL) ou próprias (owner_id = auth.uid())
create policy mensagens_modelos_insert_auth
  on public.mensagens_modelos
  for insert
  to authenticated
  with check (owner_id = auth.uid() or owner_id is null);

-- Atualizar somente as próprias
create policy mensagens_modelos_update_auth
  on public.mensagens_modelos
  for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

-- Apagar somente as próprias
create policy mensagens_modelos_delete_auth
  on public.mensagens_modelos
  for delete
  to authenticated
  using (owner_id = auth.uid());
-- =============================================
-- Mensagens: Arquivos em Base64 para envio
-- Cria tabela para armazenar arquivos codificados em base64,
-- com suporte a uso público (owner_id NULL) e por usuário autenticado.
-- =============================================

create table if not exists public.mensagens_arquivos (
  id bigint generated by default as identity primary key,
  owner_id uuid null references auth.users(id) on delete set null,
  filename text not null,
  mimetype text null,
  size bigint null,
  data_base64 text not null,
  created_at timestamptz not null default now()
);

alter table public.mensagens_arquivos enable row level security;

-- Índices úteis
create index if not exists mensagens_arquivos_owner_idx on public.mensagens_arquivos (owner_id);
create index if not exists mensagens_arquivos_created_idx on public.mensagens_arquivos (created_at desc);

-- Limpar policies antigas para não conflitar
drop policy if exists "select own message files" on public.mensagens_arquivos;
drop policy if exists "select public message files" on public.mensagens_arquivos;
drop policy if exists "insert own message files" on public.mensagens_arquivos;
drop policy if exists "insert public message files" on public.mensagens_arquivos;
drop policy if exists "delete own message files" on public.mensagens_arquivos;
drop policy if exists "delete public message files" on public.mensagens_arquivos;

-- SELECT: ver próprios arquivos (autenticado)
create policy "select own message files"
  on public.mensagens_arquivos
  for select
  to authenticated
  using (owner_id = auth.uid());

-- SELECT: ver arquivos públicos (não autenticado)
create policy "select public message files"
  on public.mensagens_arquivos
  for select
  to anon
  using (owner_id is null);

-- INSERT: inserir arquivos próprios (autenticado)
create policy "insert own message files"
  on public.mensagens_arquivos
  for insert
  to authenticated
  with check (owner_id = auth.uid());

-- INSERT: inserir arquivos públicos (não autenticado)
create policy "insert public message files"
  on public.mensagens_arquivos
  for insert
  to anon
  with check (owner_id is null);

-- DELETE: apagar arquivos próprios (autenticado)
create policy "delete own message files"
  on public.mensagens_arquivos
  for delete
  to authenticated
  using (owner_id = auth.uid());

-- DELETE: apagar arquivos públicos (não autenticado)
create policy "delete public message files"
  on public.mensagens_arquivos
  for delete
  to anon
  using (owner_id is null);

-- Observações:
-- - Para uso público (sem login), os registros devem ter owner_id = NULL.
-- - Para uso autenticado, defina owner_id = auth.uid().
-- - Considere limites de tamanho; data_base64 pode crescer. Avalie mover para Storage caso necessário.

-- =============================================
-- Conjuntos de mensagens (1–3)
-- Permite salvar um conjunto com até três textos.
-- =============================================

create table if not exists public.mensagens_conjuntos (
  id bigint generated by default as identity primary key,
  owner_id uuid null references auth.users(id) on delete set null,
  titulo text null,
  conteudos jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.mensagens_conjuntos enable row level security;

-- Índices
create index if not exists mensagens_conjuntos_owner_idx on public.mensagens_conjuntos (owner_id);
create index if not exists mensagens_conjuntos_created_idx on public.mensagens_conjuntos (created_at desc);

-- Limpar policies antigas
drop policy if exists mensagens_conjuntos_select_anon on public.mensagens_conjuntos;
drop policy if exists mensagens_conjuntos_insert_anon on public.mensagens_conjuntos;
drop policy if exists mensagens_conjuntos_delete_anon on public.mensagens_conjuntos;

drop policy if exists mensagens_conjuntos_select_auth on public.mensagens_conjuntos;
drop policy if exists mensagens_conjuntos_insert_auth on public.mensagens_conjuntos;
drop policy if exists mensagens_conjuntos_update_auth on public.mensagens_conjuntos;
drop policy if exists mensagens_conjuntos_delete_auth on public.mensagens_conjuntos;

-- Policies para usuários sem login (anon)
create policy mensagens_conjuntos_select_anon
  on public.mensagens_conjuntos
  for select
  to anon
  using (owner_id is null);

create policy mensagens_conjuntos_insert_anon
  on public.mensagens_conjuntos
  for insert
  to anon
  with check (owner_id is null);

create policy mensagens_conjuntos_delete_anon
  on public.mensagens_conjuntos
  for delete
  to anon
  using (owner_id is null);

-- Policies para usuários logados (authenticated)
create policy mensagens_conjuntos_select_auth
  on public.mensagens_conjuntos
  for select
  to authenticated
  using (owner_id = auth.uid() or owner_id is null);

create policy mensagens_conjuntos_insert_auth
  on public.mensagens_conjuntos
  for insert
  to authenticated
  with check (owner_id = auth.uid() or owner_id is null);

create policy mensagens_conjuntos_update_auth
  on public.mensagens_conjuntos
  for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

create policy mensagens_conjuntos_delete_auth
  on public.mensagens_conjuntos
  for delete
  to authenticated
  using (owner_id = auth.uid());